package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/LuD1161/agentjail/internal/approvalexec"
	"github.com/LuD1161/agentjail/internal/hostproxy"
	"github.com/LuD1161/agentjail/internal/wire"
	"github.com/spf13/cobra"
)

var approvalChallenge string
var approvalOperation string
var approvalReason string

var approvalExecCmd = &cobra.Command{
	Use:   "approval-exec --operation OPERATION --challenge ID --reason EXPLANATION",
	Short: "Redeem a one-use Codex approval (internal)",
	Long: `Redeem a one-use approval generated by AgentJail for Codex.

The required reason is displayed with this command in Codex's native
permission prompt. The operation, challenge, and reason are bound together;
editing any value invalidates the approval. This internal command is generated
by AgentJail and should not be constructed manually.`,
	Example: `  agentjail approval-exec \
    --operation shell-command \
    --challenge <one-use-challenge> \
    --reason "publishing to a package registry is irreversible; confirm intent"`,
	Hidden: true,
	Args: func(cmd *cobra.Command, args []string) error {
		if err := cobra.NoArgs(cmd, args); err != nil {
			fmt.Fprintln(cmd.ErrOrStderr(), err)
			return err
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		return runApprovalExecCommand(cmd, approvalexec.ChallengeID(approvalChallenge), approvalexec.Operation(approvalOperation), approvalexec.Reason(approvalReason))
	},
}

func init() {
	approvalExecCmd.Flags().StringVar(&approvalChallenge, "challenge", "", "One-use approval challenge")
	approvalExecCmd.Flags().StringVar(&approvalOperation, "operation", "", "Approval operation (shell-command, git-push, or host-proxy)")
	approvalExecCmd.Flags().StringVar(&approvalReason, "reason", "", "Reason shown in the Codex permission prompt")
	approvalExecCmd.SetFlagErrorFunc(func(cmd *cobra.Command, err error) error {
		fmt.Fprintln(cmd.ErrOrStderr(), err)
		return err
	})
	rootCmd.AddCommand(approvalExecCmd)
}

func runApprovalExec(challengeID approvalexec.ChallengeID, operation approvalexec.Operation, reason approvalexec.Reason) error {
	if operation == "" {
		return fmt.Errorf("agentjail approval-exec: --operation is required")
	}
	if !approvalexec.ValidOperation(operation) {
		return fmt.Errorf("agentjail approval-exec: unsupported operation %q", operation)
	}
	if challengeID == "" {
		return fmt.Errorf("agentjail approval-exec: --challenge is required")
	}
	if reason == "" || approvalexec.PrepareReason(string(reason)) != reason {
		return fmt.Errorf("agentjail approval-exec: --reason is required and must be a bounded single-line explanation")
	}
	invocation := approvalexec.BrokerInvocation{Operation: operation, ChallengeID: challengeID, Reason: reason}
	parsed, ok := approvalexec.ParseBrokerCommand(approvalexec.BrokerCommand(invocation))
	if !ok || parsed != invocation {
		return fmt.Errorf("agentjail approval-exec: malformed challenge")
	}
	conn, err := net.DialTimeout("unix", wire.DefaultSocketPath(), 500*time.Millisecond)
	if err != nil {
		return fmt.Errorf("agentjail approval-exec: policy daemon unavailable: %w", err)
	}
	defer conn.Close()
	if err := conn.SetDeadline(time.Now().Add(2 * time.Second)); err != nil {
		return fmt.Errorf("agentjail approval-exec: set deadline: %w", err)
	}
	if err := json.NewEncoder(conn).Encode(approvalexec.WireRedeemRequest{
		Type: approvalexec.RedeemRequestType, ChallengeID: challengeID, Operation: operation, Reason: reason,
	}); err != nil {
		return fmt.Errorf("agentjail approval-exec: redeem: %w", err)
	}
	scanner := bufio.NewScanner(conn)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return fmt.Errorf("agentjail approval-exec: redeem: %w", err)
		}
		return errors.New("agentjail approval-exec: daemon closed without a redemption response")
	}
	var resp approvalexec.WireRedeemResponse
	if err := json.Unmarshal(scanner.Bytes(), &resp); err != nil {
		return fmt.Errorf("agentjail approval-exec: invalid daemon response: %w", err)
	}
	if !resp.OK {
		return fmt.Errorf("agentjail approval-exec: %s", resp.Error)
	}
	if operation == approvalexec.HostProxyOperation {
		if resp.HostProxyProof == "" || resp.HostProxyExecutable == "" || len(resp.HostProxyArgv) == 0 || resp.HostProxyReason == "" {
			return errors.New("agentjail approval-exec: daemon returned an incomplete host proxy authorization")
		}
		if err := os.Chdir(resp.CWD); err != nil {
			return fmt.Errorf("agentjail approval-exec: restore working directory: %w", err)
		}
		self, err := os.Executable()
		if err != nil {
			return fmt.Errorf("agentjail approval-exec: locate broker executable: %w", err)
		}
		env := replaceEnvironment(os.Environ(), hostproxy.ProofEnvironmentName, resp.HostProxyProof)
		env = replaceEnvironment(env, hostproxy.TargetEnvironmentName, resp.HostProxyExecutable)
		argv := append([]string{filepath.Base(self), "proxy", "--reason", resp.HostProxyReason, "--"}, resp.HostProxyArgv...)
		return syscall.Exec(self, argv, env)
	}
	if resp.Command == "" {
		return errors.New("agentjail approval-exec: daemon returned an incomplete command authorization")
	}
	if err := os.Chdir(resp.CWD); err != nil {
		return fmt.Errorf("agentjail approval-exec: restore working directory: %w", err)
	}
	shell := approvalExecShell(os.Getenv)
	return syscall.Exec(shell, []string{filepath.Base(shell), "-lc", string(resp.Command)}, os.Environ())
}

func replaceEnvironment(env []string, key, value string) []string {
	prefix := key + "="
	out := make([]string, 0, len(env)+1)
	for _, entry := range env {
		if !strings.HasPrefix(entry, prefix) {
			out = append(out, entry)
		}
	}
	return append(out, prefix+value)
}

// approvalExecShell follows the host login shell selected for the Codex
// session, retaining shell syntax and login initialization for the redeemed
// command. An absent or non-absolute value fails back to the portable shell.
func approvalExecShell(getenv func(string) string) string {
	shell := getenv("SHELL")
	if filepath.IsAbs(shell) {
		return shell
	}
	return "/bin/sh"
}

func runApprovalExecCommand(cmd *cobra.Command, challengeID approvalexec.ChallengeID, operation approvalexec.Operation, reason approvalexec.Reason) error {
	err := runApprovalExec(challengeID, operation, reason)
	if err != nil {
		fmt.Fprintln(cmd.ErrOrStderr(), err)
	}
	return err
}
