//go:build linux && amd64

package seccomp

import "golang.org/x/sys/unix"

// nativeAudit pins the BPF arch guard to AUDIT_ARCH_X86_64. Critical:
// without this guard, a 32-bit syscall on x86_64 (via int 0x80) would
// be evaluated under the 64-bit numbering and could slip through.
const nativeAudit uint32 = uint32(unix.AUDIT_ARCH_X86_64)

// nativeSyscalls maps every Baseline name to the x86_64 syscall number.
// Sourced from golang.org/x/sys/unix.SYS_*; that file is autogenerated
// against the kernel UAPI so we never maintain raw integers ourselves.
//
// Coverage invariant: every entry in Baseline either appears in this
// map OR is in KnownNames-but-arch-absent (e.g. there is no
// architecture-specific entry the resolver silently drops). The
// platform-independent profile_test.go enforces the KnownNames side;
// the Linux-only profile_linux_test.go::TestCompileResolvesNative
// exercises the resolver itself.
var nativeSyscalls = map[string]uint32{
	// File I/O
	"read":       uint32(unix.SYS_READ),
	"write":      uint32(unix.SYS_WRITE),
	"open":       uint32(unix.SYS_OPEN),
	"openat":     uint32(unix.SYS_OPENAT),
	"openat2":    uint32(unix.SYS_OPENAT2),
	"close":      uint32(unix.SYS_CLOSE),
	"lseek":      uint32(unix.SYS_LSEEK),
	"pread64":    uint32(unix.SYS_PREAD64),
	"pwrite64":   uint32(unix.SYS_PWRITE64),
	"readv":      uint32(unix.SYS_READV),
	"writev":     uint32(unix.SYS_WRITEV),
	"stat":       uint32(unix.SYS_STAT),
	"fstat":      uint32(unix.SYS_FSTAT),
	"lstat":      uint32(unix.SYS_LSTAT),
	"newfstatat": uint32(unix.SYS_NEWFSTATAT),
	"statx":      uint32(unix.SYS_STATX),
	"access":     uint32(unix.SYS_ACCESS),
	"faccessat2": uint32(unix.SYS_FACCESSAT2),
	"readlink":   uint32(unix.SYS_READLINK),
	"readlinkat": uint32(unix.SYS_READLINKAT),
	"getcwd":     uint32(unix.SYS_GETCWD),
	"getdents64": uint32(unix.SYS_GETDENTS64),
	"fcntl":      uint32(unix.SYS_FCNTL),
	"dup":        uint32(unix.SYS_DUP),
	"dup2":       uint32(unix.SYS_DUP2),
	"dup3":       uint32(unix.SYS_DUP3),
	"pipe2":      uint32(unix.SYS_PIPE2),
	"umask":      uint32(unix.SYS_UMASK),
	"fstatfs":    uint32(unix.SYS_FSTATFS),
	"chdir":      uint32(unix.SYS_CHDIR),
	"fchdir":     uint32(unix.SYS_FCHDIR),

	// Memory
	"mmap":         uint32(unix.SYS_MMAP),
	"munmap":       uint32(unix.SYS_MUNMAP),
	"mprotect":     uint32(unix.SYS_MPROTECT),
	"brk":          uint32(unix.SYS_BRK),
	"madvise":      uint32(unix.SYS_MADVISE),
	"memfd_create": uint32(unix.SYS_MEMFD_CREATE),

	// Signals
	"rt_sigaction":      uint32(unix.SYS_RT_SIGACTION),
	"rt_sigprocmask":    uint32(unix.SYS_RT_SIGPROCMASK),
	"rt_sigreturn":      uint32(unix.SYS_RT_SIGRETURN),
	"sigaltstack":       uint32(unix.SYS_SIGALTSTACK),
	"kill":              uint32(unix.SYS_KILL),
	"tkill":             uint32(unix.SYS_TKILL),
	"tgkill":            uint32(unix.SYS_TGKILL),
	"pidfd_send_signal": uint32(unix.SYS_PIDFD_SEND_SIGNAL),

	// Process lifecycle
	"clone":           uint32(unix.SYS_CLONE),
	"clone3":          uint32(unix.SYS_CLONE3),
	"fork":            uint32(unix.SYS_FORK),
	"execve":          uint32(unix.SYS_EXECVE),
	"wait4":           uint32(unix.SYS_WAIT4),
	"exit":            uint32(unix.SYS_EXIT),
	"exit_group":      uint32(unix.SYS_EXIT_GROUP),
	"set_tid_address": uint32(unix.SYS_SET_TID_ADDRESS),
	"set_robust_list": uint32(unix.SYS_SET_ROBUST_LIST),
	"rseq":            uint32(unix.SYS_RSEQ),
	"arch_prctl":      uint32(unix.SYS_ARCH_PRCTL),
	"prctl":           uint32(unix.SYS_PRCTL),
	"prlimit64":       uint32(unix.SYS_PRLIMIT64),
	"getrlimit":       uint32(unix.SYS_GETRLIMIT),

	// Identity
	"uname":     uint32(unix.SYS_UNAME),
	"getuid":    uint32(unix.SYS_GETUID),
	"getgid":    uint32(unix.SYS_GETGID),
	"geteuid":   uint32(unix.SYS_GETEUID),
	"getegid":   uint32(unix.SYS_GETEGID),
	"getresuid": uint32(unix.SYS_GETRESUID),
	"getresgid": uint32(unix.SYS_GETRESGID),
	"getpid":    uint32(unix.SYS_GETPID),
	"getppid":   uint32(unix.SYS_GETPPID),
	"gettid":    uint32(unix.SYS_GETTID),
	"capget":    uint32(unix.SYS_CAPGET),

	// Time
	"clock_gettime":   uint32(unix.SYS_CLOCK_GETTIME),
	"clock_nanosleep": uint32(unix.SYS_CLOCK_NANOSLEEP),
	"nanosleep":       uint32(unix.SYS_NANOSLEEP),
	"gettimeofday":    uint32(unix.SYS_GETTIMEOFDAY),

	// Random
	"getrandom": uint32(unix.SYS_GETRANDOM),

	// Sync
	"futex":       uint32(unix.SYS_FUTEX),
	"sched_yield": uint32(unix.SYS_SCHED_YIELD),

	// I/O multiplexing
	"poll":           uint32(unix.SYS_POLL),
	"ppoll":          uint32(unix.SYS_PPOLL),
	"epoll_create1":  uint32(unix.SYS_EPOLL_CREATE1),
	"epoll_ctl":      uint32(unix.SYS_EPOLL_CTL),
	"epoll_wait":     uint32(unix.SYS_EPOLL_WAIT),
	"epoll_pwait":    uint32(unix.SYS_EPOLL_PWAIT),
	"eventfd2":       uint32(unix.SYS_EVENTFD2),
	"timerfd_create": uint32(unix.SYS_TIMERFD_CREATE),

	// Network
	"socket":      uint32(unix.SYS_SOCKET),
	"connect":     uint32(unix.SYS_CONNECT),
	"sendto":      uint32(unix.SYS_SENDTO),
	"recvfrom":    uint32(unix.SYS_RECVFROM),
	"sendmsg":     uint32(unix.SYS_SENDMSG),
	"recvmsg":     uint32(unix.SYS_RECVMSG),
	"shutdown":    uint32(unix.SYS_SHUTDOWN),
	"bind":        uint32(unix.SYS_BIND),
	"listen":      uint32(unix.SYS_LISTEN),
	"accept4":     uint32(unix.SYS_ACCEPT4),
	"getsockname": uint32(unix.SYS_GETSOCKNAME),
	"getpeername": uint32(unix.SYS_GETPEERNAME),
	"setsockopt":  uint32(unix.SYS_SETSOCKOPT),
	"getsockopt":  uint32(unix.SYS_GETSOCKOPT),

	// Misc
	"ioctl": uint32(unix.SYS_IOCTL),
}
