package agents

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

const codexExecPolicy = `# Managed by AgentJail. Do not edit this file.
# The command carries only an opaque one-use challenge; the original command
# remains in the AgentJail daemon until this prompt is approved.
prefix_rule(
    pattern = ["agentjail", "approval-exec"],
    decision = "prompt",
    justification = "AgentJail policy requires your approval for the original command.",
)
`

func codexExecPolicyPath(env Env) string {
	return filepath.Join(env.Home, ".codex", "rules", "agentjail.rules")
}

func ensureCodexExecPolicy(env Env) error {
	path := codexExecPolicyPath(env)
	existing, err := os.ReadFile(path)
	switch {
	case err == nil && bytes.Equal(existing, []byte(codexExecPolicy)):
		return nil
	case err == nil:
		return fmt.Errorf("managed execpolicy file has local changes: %s", path)
	case !os.IsNotExist(err):
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return writeFileAtomic(path, []byte(codexExecPolicy), 0o600)
}

func removeCodexExecPolicy(env Env) error {
	path := codexExecPolicyPath(env)
	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !bytes.Equal(existing, []byte(codexExecPolicy)) {
		return fmt.Errorf("preserving locally changed execpolicy file: %s", path)
	}
	return os.Remove(path)
}

func codexExecPolicyInstalled(env Env) bool {
	existing, err := os.ReadFile(codexExecPolicyPath(env))
	return err == nil && bytes.Equal(existing, []byte(codexExecPolicy))
}
