// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type DBAuditEvent struct {
	ID     int64          `json:"id"`
	Ts     string         `json:"ts"`
	Action string         `json:"action"`
	RuleID sql.NullString `json:"rule_id"`
	User   sql.NullString `json:"user"`
}

type DBDecision struct {
	ID                int64          `json:"id"`
	Ts                string         `json:"ts"`
	SessionID         string         `json:"session_id"`
	Agent             sql.NullString `json:"agent"`
	ToolName          string         `json:"tool_name"`
	Summary           sql.NullString `json:"summary"`
	Action            string         `json:"action"`
	RuleID            sql.NullString `json:"rule_id"`
	Reason            sql.NullString `json:"reason"`
	Impact            sql.NullString `json:"impact"`
	ElapsedUs         sql.NullInt64  `json:"elapsed_us"`
	Cwd               sql.NullString `json:"cwd"`
	ToolInputRedacted sql.NullString `json:"tool_input_redacted"`
}

type DBDiscoveredSkill struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Source    string `json:"source"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
	UseCount  int64  `json:"use_count"`
}

type DBDiscoveredTool struct {
	ID        int64  `json:"id"`
	Server    string `json:"server"`
	Tool      string `json:"tool"`
	Source    string `json:"source"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
}

type DBSession struct {
	SessionID     string         `json:"session_id"`
	StartTs       string         `json:"start_ts"`
	EndTs         sql.NullString `json:"end_ts"`
	Agent         sql.NullString `json:"agent"`
	Cwd           sql.NullString `json:"cwd"`
	DecisionCount int64          `json:"decision_count"`
}
