// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const countActionsBySession = `-- name: CountActionsBySession :many
-- Counts the FINAL outcome (ADR 0112): a policy verdict the OS sandbox
-- overrode is counted as what actually happened, mapped back to the
-- allow/deny/ask vocabulary the totals use. Rows with no observed final
-- outcome fall back to the policy action.
SELECT session_id,
  CASE lower(final_action)
    WHEN 'blocked' THEN 'deny'
    WHEN 'allowed' THEN 'allow'
    WHEN 'ask'     THEN 'ask'
    ELSE action
  END AS action,
  COUNT(*) AS count
FROM decisions GROUP BY session_id, 2
`

type CountActionsBySessionRow struct {
	SessionID string `json:"session_id"`
	Action    string `json:"action"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountActionsBySession(ctx context.Context) ([]CountActionsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, countActionsBySession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActionsBySessionRow{}
	for rows.Next() {
		var i CountActionsBySessionRow
		if err := rows.Scan(&i.SessionID, &i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditByTypeSince = `-- name: CountAuditByTypeSince :many
SELECT event_type, COUNT(*) AS count FROM audit_log
WHERE ts >= ? GROUP BY event_type ORDER BY count DESC
`

type CountAuditByTypeSinceRow struct {
	EventType string `json:"event_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountAuditByTypeSince(ctx context.Context, ts string) ([]CountAuditByTypeSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditByTypeSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditByTypeSinceRow{}
	for rows.Next() {
		var i CountAuditByTypeSinceRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByActionSince = `-- name: CountByActionSince :many

SELECT CASE lower(final_action)
    WHEN 'blocked' THEN 'deny'
    WHEN 'allowed' THEN 'allow'
    WHEN 'ask'     THEN 'ask'
    ELSE action
  END AS action,
  COUNT(*) AS count
FROM decisions
WHERE ts >= ?
GROUP BY 1
ORDER BY count DESC
`

type CountByActionSinceRow struct {
	Action string `json:"action"`
	Count  int64  `json:"count"`
}

// Stats aggregates (agentjail stats). Each is scoped by `ts >= ?`; pass a zero
// time formatted as RFC3339 for all-time. See AGE-213.
func (q *Queries) CountByActionSince(ctx context.Context, ts string) ([]CountByActionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countByActionSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByActionSinceRow{}
	for rows.Next() {
		var i CountByActionSinceRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByAgentSince = `-- name: CountByAgentSince :many
SELECT agent, COUNT(*) AS count FROM decisions
WHERE ts >= ? GROUP BY agent ORDER BY count DESC
`

type CountByAgentSinceRow struct {
	Agent sql.NullString `json:"agent"`
	Count int64          `json:"count"`
}

func (q *Queries) CountByAgentSince(ctx context.Context, ts string) ([]CountByAgentSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countByAgentSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByAgentSinceRow{}
	for rows.Next() {
		var i CountByAgentSinceRow
		if err := rows.Scan(&i.Agent, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDenyRulesSince = `-- name: CountDenyRulesSince :many
SELECT rule_id, COUNT(*) AS count FROM decisions
WHERE COALESCE(NULLIF(policy_action, ''), action) = 'deny' AND ts >= ?
GROUP BY rule_id
ORDER BY count DESC
`

type CountDenyRulesSinceRow struct {
	RuleID sql.NullString `json:"rule_id"`
	Count  int64          `json:"count"`
}

func (q *Queries) CountDenyRulesSince(ctx context.Context, ts string) ([]CountDenyRulesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countDenyRulesSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDenyRulesSinceRow{}
	for rows.Next() {
		var i CountDenyRulesSinceRow
		if err := rows.Scan(&i.RuleID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDistinctSessionsSince = `-- name: CountDistinctSessionsSince :one
SELECT COUNT(DISTINCT session_id) AS count FROM decisions WHERE ts >= ?
`

func (q *Queries) CountDistinctSessionsSince(ctx context.Context, ts string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctSessionsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWouldBlockByRule = `-- name: CountWouldBlockByRule :many
SELECT rule_id, would_action, tool_name, COUNT(*) AS count
FROM decisions
WHERE would_action != '' AND ts >= ?
GROUP BY rule_id, would_action, tool_name
ORDER BY count DESC
`

type CountWouldBlockByRuleRow struct {
	RuleID      sql.NullString `json:"rule_id"`
	WouldAction string         `json:"would_action"`
	ToolName    string         `json:"tool_name"`
	Count       int64          `json:"count"`
}

// Monitor-mode report: what policy would have stopped, grouped by rule. Rows
// where would_action is empty are enforce-mode decisions and are excluded.
// See ADR 0091-monitor-mode-tools.
func (q *Queries) CountWouldBlockByRule(ctx context.Context, ts string) ([]CountWouldBlockByRuleRow, error) {
	rows, err := q.db.QueryContext(ctx, countWouldBlockByRule, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountWouldBlockByRuleRow{}
	for rows.Next() {
		var i CountWouldBlockByRuleRow
		if err := rows.Scan(
			&i.RuleID,
			&i.WouldAction,
			&i.ToolName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decisionDaysSince = `-- name: DecisionDaysSince :many
SELECT CAST(substr(ts, 1, 10) AS TEXT) AS day, COUNT(*) AS count FROM decisions
WHERE ts >= ? GROUP BY day ORDER BY day ASC
`

type DecisionDaysSinceRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) DecisionDaysSince(ctx context.Context, ts string) ([]DecisionDaysSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, decisionDaysSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DecisionDaysSinceRow{}
	for rows.Next() {
		var i DecisionDaysSinceRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOldAuditLog = `-- name: DeleteOldAuditLog :exec
DELETE FROM audit_log WHERE ts < ?
`

func (q *Queries) DeleteOldAuditLog(ctx context.Context, ts string) error {
	_, err := q.db.ExecContext(ctx, deleteOldAuditLog, ts)
	return err
}

const deleteOldDecisions = `-- name: DeleteOldDecisions :exec
DELETE FROM decisions WHERE ts < ?
`

func (q *Queries) DeleteOldDecisions(ctx context.Context, ts string) error {
	_, err := q.db.ExecContext(ctx, deleteOldDecisions, ts)
	return err
}

const deleteOldSessions = `-- name: DeleteOldSessions :exec
DELETE FROM sessions WHERE start_ts < ?
`

func (q *Queries) DeleteOldSessions(ctx context.Context, startTs string) error {
	_, err := q.db.ExecContext(ctx, deleteOldSessions, startTs)
	return err
}

const getDecisionCount = `-- name: GetDecisionCount :one
SELECT COUNT(*) FROM decisions
`

func (q *Queries) GetDecisionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDecisionCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (ts, event_type, entity, detail, actor, session_id, ref_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	Ts        string         `json:"ts"`
	EventType string         `json:"event_type"`
	Entity    sql.NullString `json:"entity"`
	Detail    sql.NullString `json:"detail"`
	Actor     sql.NullString `json:"actor"`
	SessionID sql.NullString `json:"session_id"`
	RefID     sql.NullString `json:"ref_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.Ts,
		arg.EventType,
		arg.Entity,
		arg.Detail,
		arg.Actor,
		arg.SessionID,
		arg.RefID,
	)
	return err
}

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO decisions (ts, session_id, agent, tool_name, summary, action, rule_id, reason, impact, elapsed_us, cwd, tool_input_redacted, would_action, policy_action, effective_action, adapter, translation_reason)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDecisionParams struct {
	Ts                string         `json:"ts"`
	SessionID         string         `json:"session_id"`
	Agent             sql.NullString `json:"agent"`
	ToolName          string         `json:"tool_name"`
	Summary           sql.NullString `json:"summary"`
	Action            string         `json:"action"`
	RuleID            sql.NullString `json:"rule_id"`
	Reason            sql.NullString `json:"reason"`
	Impact            sql.NullString `json:"impact"`
	ElapsedUs         sql.NullInt64  `json:"elapsed_us"`
	Cwd               sql.NullString `json:"cwd"`
	ToolInputRedacted sql.NullString `json:"tool_input_redacted"`
	WouldAction       string         `json:"would_action"`
	PolicyAction      string         `json:"policy_action"`
	EffectiveAction   string         `json:"effective_action"`
	Adapter           string         `json:"adapter"`
	TranslationReason string         `json:"translation_reason"`
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.ExecContext(ctx, insertDecision,
		arg.Ts,
		arg.SessionID,
		arg.Agent,
		arg.ToolName,
		arg.Summary,
		arg.Action,
		arg.RuleID,
		arg.Reason,
		arg.Impact,
		arg.ElapsedUs,
		arg.Cwd,
		arg.ToolInputRedacted,
		arg.WouldAction,
		arg.PolicyAction,
		arg.EffectiveAction,
		arg.Adapter,
		arg.TranslationReason,
	)
	return err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT session_id, start_ts, end_ts, agent, cwd, decision_count FROM sessions ORDER BY start_ts DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]DBSession, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBSession{}
	for rows.Next() {
		var i DBSession
		if err := rows.Scan(
			&i.SessionID,
			&i.StartTs,
			&i.EndTs,
			&i.Agent,
			&i.Cwd,
			&i.DecisionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByEntity = `-- name: ListAuditLogByEntity :many
SELECT id, ts, event_type, entity, detail, actor, session_id, ref_id
FROM audit_log WHERE entity = ? ORDER BY ts DESC LIMIT ?
`

type ListAuditLogByEntityParams struct {
	Entity sql.NullString `json:"entity"`
	Limit  int64          `json:"limit"`
}

func (q *Queries) ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]DBAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByEntity, arg.Entity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBAuditLog{}
	for rows.Next() {
		var i DBAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.Entity,
			&i.Detail,
			&i.Actor,
			&i.SessionID,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogBySession = `-- name: ListAuditLogBySession :many
SELECT id, ts, event_type, entity, detail, actor, session_id, ref_id
FROM audit_log WHERE session_id = ? ORDER BY ts DESC LIMIT ?
`

type ListAuditLogBySessionParams struct {
	SessionID sql.NullString `json:"session_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListAuditLogBySession(ctx context.Context, arg ListAuditLogBySessionParams) ([]DBAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBAuditLog{}
	for rows.Next() {
		var i DBAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.Entity,
			&i.Detail,
			&i.Actor,
			&i.SessionID,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByType = `-- name: ListAuditLogByType :many
SELECT id, ts, event_type, entity, detail, actor, session_id, ref_id
FROM audit_log WHERE event_type = ? ORDER BY ts DESC LIMIT ?
`

type ListAuditLogByTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListAuditLogByType(ctx context.Context, arg ListAuditLogByTypeParams) ([]DBAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBAuditLog{}
	for rows.Next() {
		var i DBAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.Entity,
			&i.Detail,
			&i.Actor,
			&i.SessionID,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogRecent = `-- name: ListAuditLogRecent :many
SELECT id, ts, event_type, entity, detail, actor, session_id, ref_id
FROM audit_log ORDER BY ts DESC LIMIT ?
`

func (q *Queries) ListAuditLogRecent(ctx context.Context, limit int64) ([]DBAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBAuditLog{}
	for rows.Next() {
		var i DBAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.Entity,
			&i.Detail,
			&i.Actor,
			&i.SessionID,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveredSkillsAll = `-- name: ListDiscoveredSkillsAll :many
SELECT id, name, source, first_seen, last_seen, use_count FROM discovered_skills ORDER BY name
`

func (q *Queries) ListDiscoveredSkillsAll(ctx context.Context) ([]DBDiscoveredSkill, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredSkillsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBDiscoveredSkill{}
	for rows.Next() {
		var i DBDiscoveredSkill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.FirstSeen,
			&i.LastSeen,
			&i.UseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveredToolsAll = `-- name: ListDiscoveredToolsAll :many
SELECT id, server, tool, source, first_seen, last_seen FROM discovered_tools ORDER BY server, tool
`

func (q *Queries) ListDiscoveredToolsAll(ctx context.Context) ([]DBDiscoveredTool, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredToolsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBDiscoveredTool{}
	for rows.Next() {
		var i DBDiscoveredTool
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Tool,
			&i.Source,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveredToolsByServer = `-- name: ListDiscoveredToolsByServer :many
SELECT id, server, tool, source, first_seen, last_seen FROM discovered_tools WHERE server = ? ORDER BY tool
`

func (q *Queries) ListDiscoveredToolsByServer(ctx context.Context, server string) ([]DBDiscoveredTool, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredToolsByServer, server)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBDiscoveredTool{}
	for rows.Next() {
		var i DBDiscoveredTool
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Tool,
			&i.Source,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPDiscoveryStatuses = `-- name: ListMCPDiscoveryStatuses :many
SELECT server, status, last_seen FROM mcp_discovery_status ORDER BY server
`

func (q *Queries) ListMCPDiscoveryStatuses(ctx context.Context) ([]DBMCPDiscoveryStatus, error) {
	rows, err := q.db.QueryContext(ctx, listMCPDiscoveryStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DBMCPDiscoveryStatus{}
	for rows.Next() {
		var item DBMCPDiscoveryStatus
		if err := rows.Scan(&item.Server, &item.Status, &item.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCWDs = `-- name: ListDistinctCWDs :many
SELECT DISTINCT cwd FROM sessions WHERE cwd IS NOT NULL AND cwd != '' ORDER BY cwd
`

func (q *Queries) ListDistinctCWDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctCWDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var cwd sql.NullString
		if err := rows.Scan(&cwd); err != nil {
			return nil, err
		}
		items = append(items, cwd)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctMCPToolNames = `-- name: ListDistinctMCPToolNames :many
SELECT DISTINCT tool_name FROM decisions WHERE tool_name LIKE 'mcp__%' ORDER BY tool_name
`

func (q *Queries) ListDistinctMCPToolNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctMCPToolNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tool_name string
		if err := rows.Scan(&tool_name); err != nil {
			return nil, err
		}
		items = append(items, tool_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSkillInputs = `-- name: ListDistinctSkillInputs :many
SELECT DISTINCT tool_input_redacted FROM decisions WHERE tool_name = 'Skill' AND tool_input_redacted IS NOT NULL AND tool_input_redacted != ''
`

func (q *Queries) ListDistinctSkillInputs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSkillInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var tool_input_redacted sql.NullString
		if err := rows.Scan(&tool_input_redacted); err != nil {
			return nil, err
		}
		items = append(items, tool_input_redacted)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElapsedMicrosSince = `-- name: ListElapsedMicrosSince :many
SELECT elapsed_us FROM decisions
WHERE ts >= ? AND elapsed_us IS NOT NULL AND elapsed_us > 0
ORDER BY elapsed_us ASC
`

func (q *Queries) ListElapsedMicrosSince(ctx context.Context, ts string) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, listElapsedMicrosSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var elapsed_us sql.NullInt64
		if err := rows.Scan(&elapsed_us); err != nil {
			return nil, err
		}
		items = append(items, elapsed_us)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shieldDaysSince = `-- name: ShieldDaysSince :many
SELECT CAST(substr(ts, 1, 10) AS TEXT) AS day, COUNT(*) AS count FROM audit_log
WHERE event_type = 'shield.activated' AND ts >= ? GROUP BY day ORDER BY day ASC
`

type ShieldDaysSinceRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) ShieldDaysSince(ctx context.Context, ts string) ([]ShieldDaysSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, shieldDaysSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShieldDaysSinceRow{}
	for rows.Next() {
		var i ShieldDaysSinceRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscoveredSkill = `-- name: UpsertDiscoveredSkill :exec
INSERT INTO discovered_skills (name, source, first_seen, last_seen, use_count)
VALUES (?, ?, ?, ?, 1)
ON CONFLICT(name) DO UPDATE SET
    last_seen = excluded.last_seen,
    source = excluded.source,
    use_count = use_count + 1
`

type UpsertDiscoveredSkillParams struct {
	Name      string `json:"name"`
	Source    string `json:"source"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
}

func (q *Queries) UpsertDiscoveredSkill(ctx context.Context, arg UpsertDiscoveredSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoveredSkill,
		arg.Name,
		arg.Source,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const upsertDiscoveredTool = `-- name: UpsertDiscoveredTool :exec
INSERT INTO discovered_tools (server, tool, source, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(server, tool) DO UPDATE SET
    last_seen = excluded.last_seen,
    source = excluded.source
`

type UpsertDiscoveredToolParams struct {
	Server    string `json:"server"`
	Tool      string `json:"tool"`
	Source    string `json:"source"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
}

const upsertMCPDiscoveryStatus = `-- name: UpsertMCPDiscoveryStatus :exec
INSERT INTO mcp_discovery_status (server, status, last_seen)
VALUES (?, ?, ?)
ON CONFLICT(server) DO UPDATE SET
    status = excluded.status,
    last_seen = excluded.last_seen
`

type UpsertMCPDiscoveryStatusParams struct {
	Server   string `json:"server"`
	Status   string `json:"status"`
	LastSeen string `json:"last_seen"`
}

func (q *Queries) UpsertMCPDiscoveryStatus(ctx context.Context, arg UpsertMCPDiscoveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertMCPDiscoveryStatus, arg.Server, arg.Status, arg.LastSeen)
	return err
}

func (q *Queries) UpsertDiscoveredTool(ctx context.Context, arg UpsertDiscoveredToolParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoveredTool,
		arg.Server,
		arg.Tool,
		arg.Source,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (session_id, start_ts, end_ts, agent, cwd, decision_count)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT(session_id) DO UPDATE SET
    end_ts = excluded.end_ts,
    agent = COALESCE(excluded.agent, sessions.agent),
    cwd = COALESCE(excluded.cwd, sessions.cwd),
    decision_count = sessions.decision_count + 1
`

type UpsertSessionParams struct {
	SessionID string         `json:"session_id"`
	StartTs   string         `json:"start_ts"`
	EndTs     sql.NullString `json:"end_ts"`
	Agent     sql.NullString `json:"agent"`
	Cwd       sql.NullString `json:"cwd"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.SessionID,
		arg.StartTs,
		arg.EndTs,
		arg.Agent,
		arg.Cwd,
	)
	return err
}
